version: '3.1'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_DATABASE: db-emprescar

volumes:
  dbbase:






#version: '3'
#services:
#  emprescar:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    image: emprescar/api
#    ports:
#      - '8081:8080'
#      - '5005:5005'
#    environment:
#      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
#      - PROFILE=dev
#    links:
#      - db
#  db:
#    image: mysql:5.6
#    ports:
#      - '3307:3306'
#    environment:
#      - MYSQL_ROOT_HOST=%
#      - MYSQL_DATABASE=db-emprescar
#      - MYSQL_USER=root
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#    volumes:
#      - ./docker/volume_mysql:/var/lib/mysql